### ISSUE TITLE
UI improvements with the fragments and activities

### ISSUE THREAD

**Issue by EarlGre** [EarlGre/Food-Preserver#1]
Focus on getting the UI sharp and professional looking by adding sophisticated features that abide by the principles of app design.

**Comment by Tooni8282** [comment]
![app_veggies](https://user-images.githubusercontent.com/64814580/98152214-37781680-1e86-11eb-98a1-a5b9f0c6997c.png)

**Comment by Tooni8282** [comment]
![app_foodItem](https://user-images.githubusercontent.com/64814580/98152407-87ef7400-1e86-11eb-84f4-c13abbfdded5.png)

**Comment by JTownJesse** [comment]
![assasasas](https://user-images.githubusercontent.com/64864005/99157287-62c7e600-267c-11eb-8698-9df0a9f5f224.png)
Updated
