### ISSUE TITLE
Fill out search field in database

### ISSUE THREAD

**Issue by EarlGre** [EarlGre/Food-Preserver#2]
Completing the final arrangements for searching food items in Preserve It

**Comment by BobberooniTooni** [comment]
![app_favourites](https://user-images.githubusercontent.com/64814580/98152135-16afc100-1e86-11eb-9134-9a74527c14a5.png)

**Comment by Tooni8282** [comment]
![app_search](https://user-images.githubusercontent.com/64814580/98152174-23341980-1e86-11eb-8431-10588c0d399c.png)

**Comment by JTownJesse** [comment]
![xxxxx](https://user-images.githubusercontent.com/64864005/99156759-6c4f4f00-2678-11eb-9194-f5069882340e.png)

![asdasd](https://user-images.githubusercontent.com/64864005/99156841-1038fa80-2679-11eb-807e-4bffbedf8593.png)
