### ISSUE TITLE
Create canning help tab

### ISSUE THREAD

**Issue by EarlGre** [EarlGre/Food-Preserver#3]
Completing the fragments for each sub-section in help tab

**Comment by Tooni8282** [comment]
![app_help](https://user-images.githubusercontent.com/64814580/98153858-b1110400-1e88-11eb-8a22-0dedc49d049b.png)

**Comment by JTownJesse** [comment]
![ssssss](https://user-images.githubusercontent.com/64864005/99156402-66a43a00-2675-11eb-91bc-3bb124ab5d55.png)
After changes
