### ISSUE TITLE
Scrolling activity modifications

### ISSUE THREAD

**Issue by EarlGre** [EarlGre/Food-Preserver#4]
Part of UI but it can be a great boost in the aspect of Preserve It's UI.

**Comment by BobberooniTooni** [comment]
![Uploading app_help.png…]()

**Comment by JTownJesse** [comment]
![collapse](https://user-images.githubusercontent.com/64864005/99157179-abcb6a80-267b-11eb-8f96-ddd4abef3019.png)
Collapsing Tool Bar
