### ISSUE TITLE
UI Consistency and Theme for Different Activities

### ISSUE THREAD

**Issue by Tooni8282** [EarlGre/Food-Preserver#5]

**Comment by Tooni8282** [comment]
![app_fruit](https://user-images.githubusercontent.com/64814580/98153019-6d69ca80-1e87-11eb-89d9-87d20c39ba13.png)

**Comment by Tooni8282** [comment]
![app_meat](https://user-images.githubusercontent.com/64814580/98153035-722e7e80-1e87-11eb-9cf8-c9c6fe0f91e7.png)

**Comment by Tooni8282** [comment]
![app_search](https://user-images.githubusercontent.com/64814580/98153230-b4f05680-1e87-11eb-9e81-e3696cc05e39.png)

**Comment by JTownJesse** [comment]
![99157287-62c7e600-267c-11eb-8698-9df0a9f5f224](https://user-images.githubusercontent.com/64864005/99157324-a6225480-267c-11eb-8200-ca54b6beb4bf.png)
![99157179-abcb6a80-267b-11eb-8f96-ddd4abef3019](https://user-images.githubusercontent.com/64864005/99157325-a6baeb00-267c-11eb-8a3b-dd2c24571281.png)
